### ISSUE TITLE
Cap trigger efficiency at 1.0 for 2016

### ISSUE THREAD

**Issue by VourMa** [cms-susy-soft-leptons/cmgtools-lite#10]
Dividing the lepton efficiency in 2016 with the DCA efficiency so that the latter is not double counted, e.g. [here](https://github.com/cms-susy-soft-leptons/cmgtools-lite/blob/e74bdd2bc5270582d1ec0681ca515237cbca9e4d/TTHAnalysis/python/plotter/susy-sos/functionsSF.cc#L152), sometimes causes the efficiency to be greater than 1.0, due to upward statistical fluctuations in the efficiency maps. A fix should be implemented to cap the efficiency in those cases to 1.0.

**Comment by vtavolar** [comment]
Fixed in PR #14 .
