### ISSUE TITLE
Jet collection not replaced by recleaned jets in mcc-sos

### ISSUE THREAD

**Issue by Pmeiring** [cms-susy-soft-leptons/cmgtools-lite#2]
https://github.com/cms-susy-soft-leptons/cmgtools-lite/blob/b27a9c65a8f823796d0824a9fe01ff8103c008e2/TTHAnalysis/python/plotter/susy-sos/2los_cuts.txt#L13

The variable "Jet1_jetId" is not using the recleaned jets. The mcc-sos.txt does not replace the Jet collection by the recleaned ones.
Also, the friendtree does not have indices for the recleaned jets nor the id of the recleaned jets in the JetSel collection.

**Comment by VourMa** [comment]
This was fixed in [43f701f](https://github.com/vtavolar/cmgtools-lite/commit/43f701f785746a098fba450ab85f63466d761910#diff-f210d206c4d653faaa8acc0c1cf7e0f9).
